### List (index)
GET {{apiUrl}}/records
Content-Type: application/json

{
    "search": {
        "digit": 4,
        "city": "Ernserhaven"
    }
}


### Show - "access": 1
GET {{apiUrl}}/records/{{recordId1}}


### Show - "access": 0
GET {{apiUrl}}/records/{{recordId2}}


### Show2 - "access": 1
GET {{apiUrl}}/records2/{{recordId1}}


### Show2 - "access": 0
GET {{apiUrl}}/records2/{{recordId2}}
